CHALLENGE_DATA_DIR: '/content/AIC21-MTMC/datasets/AIC21_Track3_MTMC_Tracking/'
DET_SOURCE_DIR: '/content/AIC21-MTMC/datasets/detection/images/validation/S02/'
DATA_DIR: '/content/AIC21-MTMC/datasets/val'
REID_SIZE_TEST: [384, 384]
ROI_DIR: '/content/AIC21-MTMC/datasets/AIC21_Track3_MTMC_Tracking/validation/S02/'
CID_BIAS_DIR: '/content/AIC21-MTMC/datasets/AIC21_Track3_MTMC_Tracking/cam_timestamp/'
USE_RERANK: True
USE_FF: True
SCORE_THR: 0.1
MCMT_OUTPUT_TXT: 'track3_val.txt'
