DET_SOURCE_DIR: '/content/traffic_ai/AIC21-MTMC/datasets/detection/images/validation/S02/'
REID_MODEL: 'reid_model/resnet101_ibn_a_3.pth'
REID_BACKBONE: 'resnet101_ibn_a'
DET_IMG_DIR: '/content/traffic_ai/AIC21-MTMC/datasets/val/'
DATA_DIR: '/content/traffic_ai/AIC21-MTMC/datasets/detect_reid3/'
REID_SIZE_TEST: [384, 384]
